# Use 4.20 as the base
# 4.20.0-rc2 release image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:526ac23c49751f306916333ea1e8c8474a99351f2eebfe23a9115dfa4f7e0808

ARG PAYLOAD_IMAGE=quay.io/cclaudio/kata-initrds:1.1
ARG OCP_RELEASE_IMAGE=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:526ac23c49751f306916333ea1e8c8474a99351f2eebfe23a9115dfa4f7e0808

FROM ${PAYLOAD_IMAGE} as payload

FROM ${OCP_RELEASE_IMAGE}

ARG ORG
ARG ACTIVATIONKEY

RUN subscription-manager register --org ${ORG} --activationkey ${ACTIVATIONKEY}

WORKDIR /

# Install Kernel, Qemu and Kata-containers
COPY snp/rpms/ /

RUN \
  if [ -s /list_rpms_replace ]; then \
    echo "--- Replacing RPMs specified in /list_rpms_replace ---" && \
    rpm-ostree override replace $(cat /list_rpms_replace); \
  else \
    echo "--- Skipping RPM replacement: /list_rpms_replace is empty or not found ---"; \
  fi && \
  if [ -s /list_rpms_install ]; then \
    echo "--- Installing RPMs specified in /list_rpms_install ---" && \
    rpm-ostree install $(cat /list_rpms_install); \
  else \
    echo "--- Skipping RPM installation: /list_rpms_install is empty or not found ---"; \
  fi

# Copy the required tarballs from the payload stage into a temporary directory
# in the final image stage.
# It is assumed that these files exist in the root ('/') directory of the payload image.
COPY --from=payload /kata-configs.tar.gz /tmp/
COPY --from=payload /kata-initrds.tar.gz /tmp/

# Extract the files
RUN tar -xzvf /tmp/kata-configs.tar.gz -C / && \
    tar -xzvf /tmp/kata-initrds.tar.gz -C / && \
    rm /tmp/kata-configs.tar.gz /tmp/kata-initrds.tar.gz


# Selinux adjustments to provide access to sev
RUN setsebool -P container_use_devices 1

RUN rpm-ostree cleanup -m && \
    ostree container commit
