= Configure the Trustee operator

Now that the Trustee operator is installed, we need to set it up.

[#trustee-route]
== Create a route for Trustee

Create a secure route with edge TLS termination for Trustee. External ingress traffic reaches the router pods as HTTPS and passes on to the Trustee pods as HTTP.

. Create a route.
+
[source,sh,role=execute]
----
oc create route edge --service=kbs-service --port kbs-port \
  -n trustee-operator-system
----
+
NOTE: Currently, only a route with a valid CA-signed certificate is supported. You cannot use a route with self-signed certificate. In ARO, the above route works well. If you are trying this guide from an Azure self managed cluster, there is the `NodePort` option available, which consists of adding `kbsServiceType: NodePort` under `spec` in the xref:02-configure-trustee.adoc#trustee-kbsconfig[Trustee KbsConfig] (restart trustee deployment), and change `AA_KBC_PARAMS` in xref:02-configure-osc.adoc#pp-cm[peer-pods ConfigMap] to be `cc_kbc::http://your_worker_node_ip_where_trustee_is:kbs_service_nodeport`. This is not a supported approach for production and just useful for trying everything in a single cluster.

. Set the `TRUSTEE_HOST` variable. This variable will be useful later when we set the xref:02-configure-osc.adoc#pp-cm[peer-pods ConfigMap]
+
[source,sh,role=execute]
----
TRUSTEE_HOST=$(oc get route -n trustee-operator-system kbs-service \
  -o jsonpath={.spec.host})

echo $TRUSTEE_HOST
----
+
Example output:
+
[source,texinfo,subs="attributes"]
----
kbs-service-trustee-operator-system.apps.rs01nyk5.eastus.aroapp.io
----

[#trustee-secret]
== Create the Trustee authentication secret

. Create private and public keys.
+
[source,sh,role=execute]
----
mkdir trustee
cd trustee
openssl genpkey -algorithm ed25519 > privateKey
openssl pkey -in privateKey -pubout -out publicKey
cd -
----

. Create a secret with the public key.
+
[source,sh,role=execute]
----
oc create secret generic kbs-auth-public-key --from-file=./trustee/publicKey -n trustee-operator-system
----

. Check that the newly created secret exists.
+
[source,sh,role=execute]
----
oc get secret -n trustee-operator-system
----

[#trustee-cm]
== Create Trustee ConfigMap

Create the and apply the Trustee `kbs-configmap.yaml` ConfigMap.

[source,sh,role=execute]
----
cat > kbs-configmap.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: kbs-config-cm
  namespace: trustee-operator-system
data:
  kbs-config.json: |
    {
      "insecure_http" : true,
      "sockets": ["0.0.0.0:8080"],
      "auth_public_key": "/etc/auth-secret/publicKey",
      "attestation_token_config": {
        "attestation_token_type": "CoCo"
      },
      "repository_config": {
        "type": "LocalFs",
        "dir_path": "/opt/confidential-containers/kbs/repository"
      },
      "as_config": {
        "work_dir": "/opt/confidential-containers/attestation-service",
        "policy_engine": "opa",
        "attestation_token_broker": "Simple",
          "attestation_token_config": {
          "duration_min": 5
          },
        "rvps_config": {
          "store_type": "LocalJson",
          "store_config": {
            "file_path": "/opt/confidential-containers/rvps/reference-values/reference-values.json"
          }
         }
      },
      "policy_engine_config": {
        "policy_path": "/opt/confidential-containers/opa/policy.rego"
      }
    }
EOF

cat kbs-configmap.yaml
----

[source,sh,role=execute]
----
oc apply -f kbs-configmap.yaml
----

[#trustee-conf]
== Configure Trustee

You can configure the following values, policies, and secrets for Trustee:

* Reference values for the Reference Value Provider Service(**mandatory**).
* Optional: Secret for container image signature verification.
* Container image signature verification policy (**mandatory**).
* If using TDX: Provisioning Certificate Caching Service for Intel Trust Domain Extensions (TDX).
* Optional: Resource access policy.
* Optional: Attestation policy.
* Optional: Secret for custom keys for Trustee clients.

In the sections below, we will elencate how to set up all these options, but for the purpose of the workshop, setting up the mandatory settings is enough.

[#trustee-mandatory-config]
=== Minimal settings (workshop)

==== **Reference values for the Reference Value Provider Service**

**Purpose of this resource**: In an attestation scenario, the client (CoCo) collects measurements from the running software, the Trusted Execution Environment (TEE) hardware and firmware and it submits a quote with the claims to the Attestation Server (Trustee, what we are setting right now). These measurements must match the trusted digests registered to the Trustee. This process ensures that the confidential VM (CVM) is running the expected software stack and has not been tampered with. By setting reference values, the user effectively defines the trusted digest (expected values) that Trustee expects from a valid client.

You can configure reference values for the Reference Value Provider Service (RVPS) by specifying the trusted digests of your hardware platform.

[source,sh,role=execute]
----
cat > rvps-configmap.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: rvps-reference-values
  namespace: trustee-operator-system
data:
  reference-values.json: |
    [
    ]
EOF

cat rvps-configmap.yaml
----

Inside `reference-values.json` field, specify the trusted digests for your hardware platform if required. Otherwise, leave it empty. For the purpose of this workshop, you can leave it empty.

Once the reference values have been added, apply the ConfigMap.

[source,sh,role=execute]
----
oc apply -f rvps-configmap.yaml
----

==== **Container image signature verification policy**

**Purpose of this resource**: Sets wether to enforce or not the container image signature verification feature. If enabled, all containers images not signed by the trusted certificate provided in the previous step will not be run.

You must create the container image signature verification policy because signature verification is always enabled. If this policy is missing, the pods will not start.

In this workshop, we will use a policy that disables signature verification. In a production environment is of course strongly recommended to enable it.

For more information, see https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md[containers-policy.json 5, window=blank].

Create a `security-policy-config.json` according to the following examples:

* *Without signature verification:*
+
[source,sh,role=execute]
----
cat > security-policy-config.json <<EOF
{
  "default": [
  {
    "type": "insecureAcceptAnything"
  }],
  "transports": {}
}
EOF

cat security-policy-config.json
----

* *Alternatively, with signature verification (requires  a xref:02-configure-trustee.adoc#trustee-signed-policy[container image verification secret]):*
+
Define some variables first:
+
Specify the image repository for `$SECURITY_POLICY_TRANSPORT`, for example, `docker`:. For more information, see https://github.com/containers/image/blob/main/docs/containers-transports.5.md[containers-transports 5, window=blank].
+
Specify the container `$SECURITY_POLICY_REGISTRY` and `$SECURITY_POLICY_IMAGE`, for example, `quay.io` and `my-image`.
+
Use the previously defined container image signature verification secret `tag` and `type` defined as `$CONTAINER_IMAGE_SIGNATURE_TYPE` and `$CONTAINER_IMAGE_SIGNATURE_TAG`.
+
[source,sh,role=execute]
----
SECURITY_POLICY_TRANSPORT=transport
SECURITY_POLICY_REGISTRY=registry
SECURITY_POLICY_IMAGE=image
----
+
Create `security-policy-config.json`:
+
[source,sh,role=execute]
----
cat > security-policy-config.json <<EOF
{
  "default": [
      {
      "type": "insecureAcceptAnything"
      }
  ],
  "transports": {
      "$SECURITY_POLICY_TRANSPORT": {
          "$SECURITY_POLICY_REGISTRY/$SECURITY_POLICY_IMAGE":
          [
              {
                  "type": "sigstoreSigned",
                  "keyPath": "kbs:///default/$CONTAINER_IMAGE_SIGNATURE_TYPE/$CONTAINER_IMAGE_SIGNATURE_TAG"
              }
          ]
      }
  }
}
EOF

cat security-policy-config.json
----

After `security-policy-config.json` is created, create the secret with the following command:

[source,sh,role=execute]
----
oc create secret generic security-policy \
  --from-file=osc=./security-policy-config.json \
  -n trustee-operator-system
----

IMPORTANT: Do not alter the secret type, `security-policy`, or the key, `osc`.

Note that `security-policy` will be later used in the xref:02-configure-trustee.adoc#trustee-kbsconfig[KbsConfig]

[#trustee-optional-config]
=== Optional configurations

[#trustee-signed-policy]
==== **Secret for container image signature verification**

**Purpose of this resource**: This secret is only necessary if you are planning to enforce the container image signature policy. It defines which container signature to trust.

If you use container image signature verification, you must create a secret that contains the public container image signing key. The Trustee Operator uses the secret to verify the signature, ensuring that only trusted and authenticated container images are deployed in your environment.

Specify the secret `$CONTAINER_IMAGE_SIGNATURE_TYPE` (for example `img-sig`), the secret `$CONTAINER_IMAGE_SIGNATURE_TAG` (for example `pub-key`), and `$CONTAINER_IMAGE_SIGNATURE_PK`, the public container image signing key.

[source,sh,role=execute]
----
CONTAINER_IMAGE_SIGNATURE_TYPE=type
CONTAINER_IMAGE_SIGNATURE_TAG=tag
CONTAINER_IMAGE_SIGNATURE_PK=public_key_file
----

Create a secret with the following command:

[source,sh,role=execute]
----
oc create secret generic $CONTAINER_IMAGE_SIGNATURE_TYPE \
    --from-file=$CONTAINER_IMAGE_SIGNATURE_TAG=./$CONTAINER_IMAGE_SIGNATURE_PK \
    -n trustee-operator-system
----

Note that `$CONTAINER_IMAGE_SIGNATURE_TYPE` will be later used in the xref:02-configure-trustee.adoc#trustee-kbsconfig[KbsConfig]

==== **Provisioning Certificate Caching Service for TDX**

**Purpose of this resource**: If your TEE is **Intel Trust Domain Extensions (TDX)**, you must configure the Provisioning Certificate Caching Service (PCCS). The PCCS retrieves Provisioning Certification Key (PCK) certificates and caches them in a local database.

IMPORTANT: Do not use the public Intel PCCS service. Use a local caching service on-premise or on the public cloud.

[source,sh,role=execute]
----
cat > tdx-config.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: tdx-config
  namespace: trustee-operator-system
data:
  sgx_default_qcnl.conf: | \
      {
        "collateral_service": "https://api.trustedservices.intel.com/sgx/certification/v4/",
        "pccs_url": "<pccs_url>"
      }
EOF

cat tdx-config.yaml
----

For `pccs_url`, specify the PCCS URL, for example, `https://localhost:8081/sgx/certification/v4/`.

Once the `pccs_url` has been added, apply the ConfigMap.

[source,sh,role=execute]
----
oc apply -f tdx-config.yaml
----

==== **Resource access policy**

**Purpose of this resource**: Resource policies control which secrets are released and are generally scoped to the workload. They allow the user define which attested workload has access to which resource, to avoid that the wrong client accesses data that it is not supposed to.

In this example below we are creating a simple policy that accepts any request that doesn't come from the sample attester, ie an attester (client) that does not use TEE. For more information about resource access policies, and how to create stronger ones, look https://confidentialcontainers.org/docs/attestation/policies/#resource-policies[here, window=blank]

[source,sh,role=execute]
----
cat > resourcepolicy-configmap.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-policy
  namespace: trustee-operator-system
data:
  policy.rego: |
    package policy
    default allow = false
    allow {
      input["tee"] != "sample"
    }
EOF

cat resourcepolicy-configmap.yaml
----

Once the policy has been implemented, apply the ConfigMap.

[source,sh,role=execute]
----
oc apply -f resourcepolicy-configmap.yaml
----

==== **Attestation policy**

**Purpose of this resource**: An attestation policy defines which part of the attestation report sent by the client (CoCo) is important for the Attester (Trustee), and how to compare the report with the reference values.

By default, Trustee has already an attestation policy. You can overwrite the default one by creating your own attestation policy.

[source,sh,role=execute]
----
cat > attestation-policy.yaml <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: attestation-policy
  namespace: trustee-operator-system
data:
  default.rego: |
     package policy
     import future.keywords.every

     default allow = false

     allow {
        every k, v in input {
            judge_field(k, v)
        }
     }

     judge_field(input_key, input_value) {
        has_key(data.reference, input_key)
        reference_value := data.reference[input_key]
        match_value(reference_value, input_value)
     }

     judge_field(input_key, input_value) {
        not has_key(data.reference, input_key)
     }

     match_value(reference_value, input_value) {
        not is_array(reference_value)
        input_value == reference_value
     }

     match_value(reference_value, input_value) {
        is_array(reference_value)
        array_include(reference_value, input_value)
     }

     array_include(reference_value_array, input_value) {
        reference_value_array == []
     }

     array_include(reference_value_array, input_value) {
        reference_value_array != []
        some i
        reference_value_array[i] == input_value
     }

     has_key(m, k) {
        _ = m[k]
     }
EOF

cat attestation-policy.yaml
----

NOTE: For the `package policy`, the attestation policy follows the https://www.openpolicyagent.org/docs/latest/policy-language/[Open Policy Agent, window=blank] specification. In this example, the attestation policy compares the claims provided in the attestation report to the reference values registered in the RVPS database. The attestation process is successful only if all the values match.

Once you defined your own policy, apply it.

[source,sh,role=execute]
----
oc apply -f attestation-policy.yaml
----

[#trustee-key]
== Add a secret to Trustee

Populate Trustee with secret(s) that are then managed by the above policies and if attestation is successful, are sent to the client(s) (CoCo). For example, a Confidential Container image/workload could be encrypted, and the key to decrypt it is stored inside the Trustee and provided only if attestation is successful. In this section, we will show how to add the key into Trustee.


**Prerequisites:** You have created one or more custom keys.

Define secret name and values. In this example, the `kbsres1` secret has two entries (`key1`, `key2`), which the clients retrieve. You can add additional secrets according to your requirements by using the same format.

Create first the key:
[source,sh,role=execute]
----
openssl rand 128 > key.bin
----

We will add `key1` as a simple string containing the text `Confidential_Secret!`, and `key2` as `key.bin`.

[source,sh,role=execute]
----
oc create secret generic kbsres1 \
  --from-literal key1=Confidential_Secret! \
  --from-literal key2=key.bin \
  -n trustee-operator-system
----

Note that `kbsres1` will be later used in the xref:02-configure-trustee.adoc#trustee-kbsconfig[KbsConfig]

[#trustee-kbsconfig]
== Create the KbsConfig custom resource

To complete Trustee setup, you must create a `KbsConfig`.

[source,sh,role=execute]
----
cat > kbsconfig-cr.yaml <<EOF
apiVersion: confidentialcontainers.org/v1alpha1
kind: KbsConfig
metadata:
  labels:
    app.kubernetes.io/name: kbsconfig
    app.kubernetes.io/instance: kbsconfig
    app.kubernetes.io/part-of: trustee-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: trustee-operator
  name: kbsconfig
  namespace: trustee-operator-system
spec:
  kbsConfigMapName: kbs-config-cm
  kbsAuthSecretName: kbs-auth-public-key
  kbsDeploymentType: AllInOneDeployment
  kbsRvpsRefValuesConfigMapName: rvps-reference-values
  kbsSecretResources: ["kbsres1", "security-policy"]
#  kbsResourcePolicyConfigMapName: resource-policy
# tdxConfigSpec:
#   kbsTdxConfigMapName: tdx-config
# kbsAttestationPolicyConfigMapName: attestation-policy
# kbsServiceType: <service_type>
EOF

cat kbsconfig-cr.yaml
----

If you did the optional steps:

* For enforced container image signature verification, extend `kbsSecretResources` list to also have the value of `$CONTAINER_IMAGE_SIGNATURE_TYPE`.
* For custom resource policy, define `kbsResourcePolicyConfigMapName`.
* For TDX PCCS define the `tdxConfigSpec` section
* For custom attestation policy define `kbsAttestationPolicyConfigMapName`
* Define `kbsServiceType` if you created a service type other than the default `ClusterIP` service to expose applications within the cluster external traffic. You can specify `NodePort`, `LoadBalancer`, or `ExternalName`.

Once the KbsConfig has been configured, apply it.

[source,sh,role=execute]
----
oc apply -f kbsconfig-cr.yaml
----

=== Verification

Verify the Trustee configuration by checking the Trustee pods and logs.

. Check that both pods are up and running:
+
[source,sh,role=execute]
----
oc get pods -n trustee-operator-system
----
+
Expected output:
+
[source,texinfo,subs="attributes"]
----
NAME                                                   READY   STATUS    RESTARTS   AGE
trustee-deployment-8585f98449-9bbgl                    1/1     Running   0          22m
trustee-operator-controller-manager-5fbd44cd97-55dlh   2/2     Running   0          59m
----

. Check the KBS pod logs
+
[source,sh,role=execute]
----
POD_NAME=$(oc get pods -l app=kbs -o jsonpath='{.items[0].metadata.name}' -n trustee-operator-system)

oc logs -n trustee-operator-system $POD_NAME
----
+
Expected output:
[source,texinfo,subs="attributes"]
----
[2024-05-30T13:44:24Z INFO  kbs] Using config file /etc/kbs-config/kbs-config.json
[2024-05-30T13:44:24Z WARN  attestation_service::rvps] No RVPS address provided and will launch a built-in rvps
[2024-05-30T13:44:24Z INFO  attestation_service::token::simple] No Token Signer key in config file, create an ephemeral key and without CA pubkey cert
[2024-05-30T13:44:24Z INFO  api_server] Starting HTTPS server at [0.0.0.0:8080]
[2024-05-30T13:44:24Z INFO  actix_server::builder] starting 4 workers
[2024-05-30T13:44:24Z INFO  actix_server::server] Tokio runtime found; starting in existing Tokio runtime
----
