= {lab_name}

Red Hat https://docs.redhat.com/en/documentation/openshift_sandboxed_containers[Openshift sandboxed containers, window=blank] provides the capability to run https://www.redhat.com/en/blog/learn-about-confidential-containers[**Confidential Containers (CoCo)**, window=blank]. Confidential Containers are containers deployed within an isolated hardware enclave protecting data and code from privileged users such as cloud or cluster administrators. The https://confidentialcontainers.org/[CNCF Confidential Containers project, window=blank] is the foundation for the OpenShift CoCo solution.Note that CoCo is an additional feature provided by OpenShift sandboxed containers, and consequently, it's available through the OpenShift sandboxed containers operator.

Please refer to the https://www.redhat.com/en/blog/exploring-openshift-confidential-containers-solution[Exploring the OpenShift Confidential Containers solution, window=blank] blogpost for more information.

In this workshop, we are also showing another operator, the **confidential compute attestation operator** (also known as `Trustee`), which can verify the trustworthiness of TEEs remotely. For more information, please refer to https://www.redhat.com/en/blog/introducing-confidential-containers-trustee-attestation-services-solution-overview-and-use-cases[this blogpost, window=blank].

We will show how to set up the Trustee and OSC operator and run a simple hello-openshift **Confidential Container** running with the *kata-remote* runtime class (peer pods solution). This effectively means that the hello-openshift container runs in a **separate**, **confidential**, **independent** virtual machine, and not in the worker node. In a another example, we will also show how **attestation** and **secure key retrieval** worflow happens between a CoCo pod and Trustee.

The goal of this workshop is to provide the user not only an environment and documentation to test CoCo, but also provide additional explanations on the design choices behind some options and the benefit they bring to the overall user experience. CoCo is designed to bring **confidential computing** at kubernetes level, making it **as simple as possible** while preserving all security benefits that confidential computing brings.

Before starting this workshop, we suggest to read the following blogposts to get a background on CoCo:

* https://www.redhat.com/en/blog/what-confidential-containers-project[What is the Confidential Containers project?, window=blank]
* https://www.redhat.com/en/blog/exploring-openshift-confidential-containers-solution[Exploring the OpenShift Confidential Containers solution, window=blank]
* https://www.redhat.com/en/blog/use-cases-and-ecosystem-openshift-confidential-containers[Use cases and ecosystem for OpenShift Confidential Containers, window=blank]
* https://www.redhat.com/en/blog/understanding-confidential-containers-attestation-flow[Understanding the Confidential Containers Attestation Flow, window=blank]

All blogposts are under this https://www.redhat.com/en/blog/learn-about-confidential-containers[blog series, window=blank].

[#credentials]
== Setting up the environment

. Navigate to the console website: {aro_console}[Openshift Console, window=blank]

. Login as administrator:
* *Username:* {aro_kube_username}
* *Password:* {aro_kube_password}

. Go into the terminal on the right and run the following commands:
* Log into azure CLI: `az login --service-principal -u {azure_service_principal_id} -p {azure_service_principal_password} --tenant {azure_tenant_id}`
* Export the `AZURE_RESOURCE_GROUP` variable. It will needed when setting up the operator:
`export AZURE_RESOURCE_GROUP={azure_resource_group}`

**Next:** This workshop follows a different approach from the official documentation, and in order to set up the whole system for CoCo only once, we recommend starting with Trustee installation and configuration. Only then we can configure OSC to interface directly with Trustee.
