FROM registry.access.redhat.com/ubi10:latest

COPY dcap-registration-flow /usr/bin

RUN  dnf install --nogpgcheck --assumeyes tdx-qgs sgx-pckid-tool

ENTRYPOINT ["/opt/intel/tdx-qgs/qgs", "--no-daemon"]
