FROM registry.access.redhat.com/ubi10:10.1-1776646961

COPY dcap-registration-flow /usr/bin

RUN  dnf install --nogpgcheck --assumeyes tdx-qgs sgx-pckid-tool

# Red Hat labels
LABEL name="openshift-sandboxed-containers/osc-tdx-qgs" \
cpe="cpe:/a:redhat:confidential_compute_attestation:1.12::el9" \
version="1.12" \
com.redhat.component="osc-tdx-qgs" \
summary="Intel TDX Quote Generation Service (QGS)" \
maintainer="redhat@redhat.com" \
description="Intel TDX Quote Generation Service (QGS) for Openshift Sandboxed Containers" \
io.k8s.display-name="openshift-sandboxed-containers-tdx-qgs" \
io.k8s.description="Intel TDX Quote Generation Service (QGS) for Openshift Sandboxed Containers" \
io.openshift.tags=""

ENTRYPOINT [ "/usr/sbin/qgs", "--no-daemon"]
