FROM registry.access.redhat.com/ubi10:latest

COPY dcap.repo .
COPY dcap-registration-flow /usr/bin

RUN dnf config-manager --add-repo dcap.repo && \
    dnf install --assumeyes tdx-qgs sgx-pckid-tool

ENTRYPOINT ["/opt/intel/tdx-qgs/qgs", "--no-daemon"]
