# podvm_payload image from where we get kata binaries artifacts, e.g. pause-bundle, kata-agent and guest components
# Must be RHEL 10 based
PODVM_PAYLOAD_IMAGE=quay.io/redhat-user-workloads/ose-osc-tenant/osc-podvm-payload:osc-podvm-payload-on-push-sptmf-build-image-index
# Base image used to build all initrds
# Must be RHEL 10 based
INITRD_BUILD_BASE_IMAGE=localhost/rhel10-nvidia-drivers:580.82.07
# kernel-core package version to be installed in the $(uname -r) format
# Must be RHEL 10 based
KERNEL_UNAME=6.12.0-55.39.1.el10_0.x86_64
# kata-containers rpm filename to be installed. It must be relative to the current directory
# Must be based on the same RHEL as the RHCOS installed in the node
KATA_RPM_FILENAME=kata-containers-3.21.0-2.rhaos4.21.el9.x86_64.rpm
