# kernel-core package version to be installed in the $(uname -r) format
KERNEL_UNAME=6.12.0-55.39.1.el10_0.x86_64
# kata-containers rpm filename to be installed. It must be relative to the current directory
KATA_RPM_FILENAME=kata-containers-3.21.0-1.rhaos4.21.el9.x86_64.rpm
