# Use rhcos layerd image with kata-containers rpm for coco installed
ARG RHCOSIMAGE
FROM $RHCOSIMAGE

ARG CERTSFILE
ARG AUTHFILE

ENV CERTSFILE=${CERTSFILE}
ENV AUTHFILE=${AUTHFILE}

WORKDIR /

COPY ${CERTSFILE} /
COPY ${AUTHFILE} /

RUN if [ ${CERTSFILE} ]; then \
        echo "CERTSFILE=/${CERTSFILE}" >> /envfile; \
    else \
        echo "CERTSFILE=" >> /envfile; \
    fi && \
    if [ ${AUTHFILE} ]; then \
        echo "AUTHFILE=/${AUTHFILE}" >> /envfile; \
    else \
        echo "AUTHFILE=" >> /envfile; \
    fi

# [Re]create initrd
RUN bash -c 'ls /lib/modules/*/vmlinu* | cut -d "/" -f 4 > /tmp/kernel_version' && \
    KVER=$(cat /tmp/kernel_version) && \
    . /envfile && \
    CA_CERTS=${CERTSFILE} REG_AUTH=${AUTHFILE} \
    CC_GUEST=1 IMAGE_TOPDIR=/usr/share/kata-containers \
    /usr/libexec/kata-containers/osbuilder/kata-osbuilder.sh -k ${KVER} 

RUN rpm-ostree cleanup -m && \
    ostree container commit
