FROM quay.io/centos/centos:stream9

ARG DCAP_VERSION=1.22

WORKDIR /opt/intel
RUN curl https://download.01.org/intel-sgx/sgx-dcap/${DCAP_VERSION}/linux/distro/centos-stream9/sgx_rpm_local_repo.tgz | tar zx && \
    dnf config-manager --add-repo file:///opt/intel/sgx_rpm_local_repo && \
    dnf install --nogpgcheck --assumeyes --setopt=install_weak_deps=False sgx-pck-id-retrieval-tool && \
    dnf config-manager --disable opt_intel_sgx_rpm_local_repo && \
    rm -r /opt/intel/sgx_rpm_local_repo

COPY dcap-registration-flow /usr/bin

ENTRYPOINT ["/usr/bin/dcap-registration-flow"]
