FROM registry.access.redhat.com/ubi9:latest

ARG DCAP_VERSION=1.23

WORKDIR /opt/intel
RUN curl https://download.01.org/intel-sgx/sgx-dcap/${DCAP_VERSION}/linux/distro/rhel9.4-server/sgx_rpm_local_repo.tgz | tar zx && \
    rpm --import https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key && \
    dnf config-manager --add-repo file:///opt/intel/sgx_rpm_local_repo && \
    dnf install --assumeyes sgx-pck-id-retrieval-tool && \
    dnf config-manager --disable opt_intel_sgx_rpm_local_repo && \
    rm -r /opt/intel/sgx_rpm_local_repo

COPY dcap-registration-flow /usr/bin

ENTRYPOINT ["/usr/bin/dcap-registration-flow"]
