FROM registry.access.redhat.com/ubi10/ubi:10.1-1762189261

# Uncomment the below instructions when running the build from an 
# unregistered host
#RUN --mount=type=secret,id=org,dst=/run/secrets/org \
#    --mount=type=secret,id=key,dst=/run/secrets/key \
#    set +x && \
#    subscription-manager register \
#      --org=$(cat /run/secrets/org) \
#      --activationkey=$(cat /run/secrets/key)

RUN dnf install -y \
   nfs-utils \
   iscsi-initiator-utils \
   e2fsprogs \
   xfsprogs \
   util-linux-core \
   cryptsetup

# Red Hat labels
LABEL name="openshift-sandboxed-containers/osc-storage-helper" \
cpe="cpe:/a:redhat:confidential_compute_attestation:1.11::el9" \
version="1.11" \
com.redhat.component="osc-storage-helper" \
summary="Openshift Sandboxed Containers Storage Helper" \
maintainer="redhat@redhat.com" \
description="Openshift Sandboxed Containers Storage Helper" \
io.k8s.display-name="openshift-sandboxed-containers-storage-helper" \
io.k8s.description="Openshift Sandboxed Containers Storage Helper" \
io.openshift.tags=""

#Uncomment the below line when using subscription-manager explicitly
#RUN subscription-manager unregister
