FROM registry.access.redhat.com/ubi9/go-toolset:1.25.8-1775491036 as builder
WORKDIR /app
COPY luks_main.go .
RUN go mod init luks-helper && go build -o luks-helper .

FROM registry.access.redhat.com/ubi10:10.1-1775011151
COPY --from=builder /app/luks-helper /usr/local/bin/luks-helper

# Uncomment the below instructions when running the build from an 
# unregistered host
#RUN --mount=type=secret,id=org,dst=/run/secrets/org \
#    --mount=type=secret,id=key,dst=/run/secrets/key \
#    set +x && \
#    subscription-manager register \
#      --org=$(cat /run/secrets/org) \
#      --activationkey=$(cat /run/secrets/key)

RUN dnf install -y \
   nfs-utils \
   iscsi-initiator-utils \
   e2fsprogs \
   xfsprogs \
   util-linux-core \
   cryptsetup

# Red Hat labels
LABEL name="openshift-sandboxed-containers/osc-storage-helper" \
cpe="cpe:/a:redhat:confidential_compute_attestation:1.12::el9" \
version="1.12" \
com.redhat.component="osc-storage-helper" \
summary="Openshift Sandboxed Containers Storage Helper" \
maintainer="redhat@redhat.com" \
description="Openshift Sandboxed Containers Storage Helper" \
io.k8s.display-name="openshift-sandboxed-containers-storage-helper" \
io.k8s.description="Openshift Sandboxed Containers Storage Helper" \
io.openshift.tags=""

#Uncomment the below line when using subscription-manager explicitly
#RUN subscription-manager unregister
