FROM registry.access.redhat.com/ubi9/nodejs-20:latest AS builder

RUN unzip /cachi2/output/deps/generic/dcap-source.zip

WORKDIR SGXDataCenterAttestationPrimitives-DCAP_1.23/tools/PCKCertSelection/
RUN mkdir -p ../../prebuilt/openssl/inc \
    && mkdir -p ../../QuoteGeneration/pccs/lib \
    && make -C PCKCertSelectionLib \
    && cp ./out/libPCKCertSelection.so ../../QuoteGeneration/pccs/lib

WORKDIR ../../QuoteGeneration/pccs
RUN . /cachi2/output/hermeto.env && npm config set engine-strict true \
    && npm install

FROM registry.access.redhat.com/ubi9/nodejs-20:latest

WORKDIR intel/pccs
COPY --from=builder --chown=default:1001 /opt/app-root/src/SGXDataCenterAttestationPrimitives-DCAP_1.23/QuoteGeneration/pccs .

ENTRYPOINT ["/usr/bin/node", "pccs_server.js"]
