FROM registry.access.redhat.com/ubi10/nodejs-22:10.1-1776735920 AS builder
USER root

WORKDIR pccs
COPY DCAP/ ./

RUN dnf install -y nodejs-devel && ln -s /usr/include/node/config-x86_64.gypi /usr/include/node/config.gypi

WORKDIR service
COPY package-lock.json .
COPY package.json .
RUN npm config set engine-strict true \
    && npm_config_nodedir=/usr npm install --build-from-source --loglevel=silly

FROM registry.access.redhat.com/ubi10/nodejs-22-minimal:10.1-1776863707

WORKDIR /opt/intel/pccs

COPY --from=builder --chown=1001:users /opt/app-root/src/pccs/service .
COPY --chown=1001:users default.json config/
COPY --chown=1001:users custom-environment-variables.json config/

# Red Hat labels
LABEL name="openshift-sandboxed-containers/osc-pccs" \
cpe="cpe:/a:redhat:confidential_compute_attestation:1.12::el9" \
version="1.12" \
com.redhat.component="osc-pccs" \
summary="Intel SGX Provisioning Certificate Caching Service (PCCS)" \
maintainer="redhat@redhat.com" \
description="Intel SGX Provisioning Certificate Caching Service (PCCS) for Openshift Sandboxed Containers" \
io.k8s.display-name="openshift-sandboxed-containers-pccs" \
io.k8s.description="Intel SGX Provisioning Certificate Caching Service (PCCS) for Openshift Sandboxed Containers" \
io.openshift.tags=""

ENTRYPOINT ["/usr/bin/node", "pccs_server.js"]
